# Change these first
owner: Bumer-32 # Your GitHub organization or username, where this repository lives
repo: lumivoid.pp.ua-Uptime # The name of this repository

sites:
  - name: Lumivoid
    url: https://lumivoid.pp.ua
  - name: Lumivoid maven
    url: https://maven.lumivoid.pp.ua

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.lumivoid.pp.ua
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Lumivoid uptime
  introTitle: "Lumivoid uptime by upptime"
  introMessage: Here you can check downtime of [lumivoud](https://lumivoid.pp.ua)
  navbar:
    - title: Lumivoid
      href: https://lumivoid.pp.ua
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
